#!/bin/sh

alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias ip="ip -color=auto"
alias dots='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias cam='devour mpv av://v4l2:/dev/video0 --profile=low-latency --untimed'
