export PATH=$PATH:~/.local/bin/
export EDITOR=nvim
# export SVDIR=$HOME/service/

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export SSRC="$HOME/.local/src"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export XAUTHORITY="$XDG_CONFIG_HOME/x11/Xauthority"
export XRESOURCES="$XDG_CONFIG_HOME/x11/Xresources"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

#MPD daemon start on tty login
[ ! -s ~/.config/mpd/pid ] && mpd
