export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export PATH=$PATH:~/.local/bin/
export EDITOR=nvim
export SVDIR=$HOME/service/

#MPD daemon start (if no other user instance exists)
[ ! -s ~/.config/mpd/pid ] && mpd
