#!/bin/sh

while read file
do
	case "$1" in
    # "C-r")
    #   convert
		"C-d")
			mv "$file" ~/pix/.trash ;;
		"C-c")
			echo "$file" | xclip -sel c ;;
    "s")
      setwall "$file" ;;
	esac
done
